### ISSUE TITLE
Missing Image 

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Website#1]
Load
http://toaelectronics.com/products/wireless-microphones

See missing image

![missing-image-001](https://cloud.githubusercontent.com/assets/6641267/7499451/9602804e-f3dc-11e4-96a8-b406026f27fb.jpg)

**Comment by ecommarato** [comment]
This should be deferred to Bridget for preference on the image.  She can also upload a picture through the CMS

**Comment by TOABridget** [comment]
Image added.
