### ISSUE TITLE
Nothing linked on Connect with Us frame

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Website#10]
load home page
Click on anything in the Connect with Us frame
Result: Nothing is hyper linked
![missing-image-009](https://cloud.githubusercontent.com/assets/6641267/7501448/dbadc4ee-f3e8-11e4-86d5-af69bc05b242.jpg)

**Comment by ecommarato** [comment]
This appears to be a content question for Bridget.  I don't know what these items should link to!

**Comment by TOABridget** [comment]
Where can I find this so I can edit?

**Comment by ecommarato** [comment]
This is under Sidebar (called Frontpage middle)

**Comment by TOABridget** [comment]
Great, thanks!
