### ISSUE TITLE
Missing images /line-input-modules page

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Website#104]
Home » Products » Amplifiers » 900 Series Modules » Line Input Modules
Load: 
http://www.toaelectronics.com/products/Amplifiers/900-series-modules-category/line-input-modules

Result: missing images for (Unbalanced Line Input with High/Low Cut Filters U-03RS) and 
(Unbalanced Line Input with Variable Mute-Receive Depth U-12S)

**Comment by TOABridget** [comment]
I do not have image for these.
