### ISSUE TITLE
/a-2240-integrated-mixer-power-amplifier missing images

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Website#107]
Home » Products » Amplifiers » Integrated Mixer / Power Amplifier
Load: http://www.toaelectronics.com/products/Amplifiers/a-2240-integrated-mixer-power-amplifier

Result: Scroll images and product images missing.
NOTE: Erin, if I understand correctly, you have been repairing the scroll bugs and Bridget will need to correct the static images.

**Comment by ecommarato** [comment]
The images appear to be EPS.  The scroller only supports JPG and PNG images.  I have removed the two EPS images from the front end display.

**Comment by rescobar2** [comment]
The scroll feature was removed. Is this expected?

**Comment by ecommarato** [comment]
Yes, EPS images are not supported in the scroller.

**Comment by rescobar2** [comment]
verified as fixed 7-28-15
