### ISSUE TITLE
/sx-2000ao-audio-output-unit scroll missing images

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Website#108]
Home » Products » SX-2000 Series Audio Management System » SX-2000AO Audio Output Unit

Load:
http://www.toaelectronics.com/products/sx-2000-series-audio-management-system/sx-2000ao-audio-output-unit

Result: Scroll images missing

**Comment by ecommarato** [comment]
I see both images.  Do you see them today?

**Comment by rescobar2** [comment]
Works in IE 9 Windows but not Chrome Version 43.0.2357.130 m
A ctrl F5 will cause image to appear for a a fraction of a second

**Comment by ecommarato** [comment]
Should be working now

**Comment by rescobar2** [comment]
verified as fixed 7-28-15
