### ISSUE TITLE
Data Library on home page not linked

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Website#11]
Open home page and review Data Library
Result: There is not a link that takes you to the Data Library
![missing-image-010](https://cloud.githubusercontent.com/assets/6641267/7501504/3890f8d4-f3e9-11e4-9f8a-dbf7a20b7338.jpg)

**Comment by rescobar2** [comment]
Also the Data Library now has a typo since reported
![image-019](https://cloud.githubusercontent.com/assets/6641267/7601188/d670d4c4-f8c7-11e4-9a74-63d1e269cfe0.jpg)

**Comment by ecommarato** [comment]
Added the link!
