### ISSUE TITLE
/s44-rx page scroll images not loading

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Website#112]
Load: 
http://www.toaelectronics.com/products/wireless-microphones/trantec-wireless-s4-4-series/s44-rx

Result: scroll images not loading

**Comment by ecommarato** [comment]
I see both images in the scrolling area.  Maybe it was a temporary glitch?  Do you see them today?

**Comment by rescobar2** [comment]
It appears in IE 9 Windows but not Chrome Version 43.0.2357.130 m
I do Ctrl F5 and the image appears for a fraction of a second then disapears.

**Comment by ecommarato** [comment]
Should be working now..

**Comment by rescobar2** [comment]
Verified as fixed 7-28-15
