### ISSUE TITLE
SR-S image missing from http://toaelectronics.com/products/Pro-Audio-Speakers

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Website#12]
Load http://toaelectronics.com/products/Pro-Audio-Speakers
Result: SR-S image missing
![missing-image-011](https://cloud.githubusercontent.com/assets/6641267/7501557/a679594a-f3e9-11e4-96f1-825f781a044d.jpg)

**Comment by TOABridget** [comment]
Image added.
