### ISSUE TITLE
Module Text Box

### ISSUE THREAD

**Issue by TOABridget** [westoforange/TOA-Website#125]
Some products only need a product description and a product feature box, while others need one more box for other information that needs to come after. Right now, we don't have that option and information is getting lost to customers. Is there any way we can get another box added to the product page that's optional for more information?

**Comment by ecommarato** [comment]
Can the additional info be added below the content in "product features" or does it need a totally new text area?

**Comment by TOABridget** [comment]
Information is not necessarily a "Product Feature", and having in that box gives the impression that it is. There are a few products that have so much information on page that the half sized box that the "Product Features" is in is not sufficient and they do in fact need a separate text box to the full width to accommodate all of the information accordingly.

**Comment by ecommarato** [comment]
Added an "Additional Information" box to the products template.  It will appear after the other other textboxes.  Try it out and let me know how it goes or if you need any additional edits.
![screen shot 2015-08-10 at 10 40 26 am](https://cloud.githubusercontent.com/assets/6640152/9173651/818824ee-3f49-11e5-96f6-865bd9b14604.png)
![screen shot 2015-08-10 at 10 40 16 am](https://cloud.githubusercontent.com/assets/6640152/9173652/81911356-3f49-11e5-9633-adc3cdab979b.png)

**Comment by rescobar2** [comment]
assigned to Rick to verify

**Comment by chezshore** [comment]
Rick, I think we can close this.

**Comment by rescobar2** [comment]
Closing
