### ISSUE TITLE
SR-S Accessories image missing

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Website#13]
Load: http://toaelectronics.com/products/Pro-Audio-Speakers/sr-s-series-slim-line-array-speakers
Result: SR-S Accessories image missing
![missing-image-012](https://cloud.githubusercontent.com/assets/6641267/7501626/30b47b58-f3ea-11e4-946e-b87885c10c69.jpg)

**Comment by TOABridget** [comment]
Image added.
