### ISSUE TITLE
n-8000ex_ce_mt1e.pdf not on site

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Website#136]
Load:
http://www.toaelectronics.com/products/intercom-systems/system-exchanges/n-8000ex
Click on Manual > Operating Instructions
Result: Page not found.

Note: This is the file which should be available "n-8000ex_ce_mt1e.pdf"
You can get it from:
T:\MARKETING\Personal Folders\Rick Escobar\Products\Intercom\000-For Web SIte\000-manual

**Comment by TOABridget** [comment]
@rescobar2  Not able to upload!

**Comment by rescobar2** [comment]
Why will it not upload? File size problem?

**Comment by TOABridget** [comment]
FTP tells me it's unable to connect. It connected the other day, but now it will not anymore.

**Comment by rescobar2** [comment]
Bridget, you should be able to upload now. Issue was with FTP permissions.

**Comment by TOABridget** [comment]
Is the correct file there? It's been so back and forth I'm not sure if I did this one or not yet. Please check and respond here.
