### ISSUE TITLE
My Download cart is cleared after a Download

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Website#138]
Add items to cue
Go to MyDownloads, enter email and click GO.
Go to any other page and return to MyDownloads page. http://www.toaelectronics.com/downloads
Result: All downloads are cleared.
NOTE: I believe the cart should be cleared after a download but the user should be notified of this feature. Just a text box would be fine.

**Comment by ecommarato** [comment]
Added a text box to inform them that their downloads have been cleared

**Comment by rescobar2** [comment]
Verified as fixed, closing
