### ISSUE TITLE
Design Support Image Missing

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Website#14]
Load: http://toaelectronics.com/support
Result: Design Support image is missing
![missing-image-013](https://cloud.githubusercontent.com/assets/6641267/7501720/158a4e6a-f3eb-11e4-8cf9-0bea65a9f0d9.jpg)

**Comment by ecommarato** [comment]
Fixed!

**Comment by rescobar2** [comment]
verified as fixed closing
