### ISSUE TITLE
Meta Data not specific for products

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Website#141]
The product meta data is not specific to each product. Appears to to be a large collection of TOA text from an unknown source. The issue is global through the site.

Example: open 
URL http://www.toaelectronics.com/products/wired-microphones/em-series-presentation-microphones/em-700

In Chrome right click to "View  Page Source" See lines 35 and 37

```
   <meta name="description"
   <meta name="keywords"
```

Result: Meta data is not specific to the product. 
NOTE: Bridget had discovered this, please speak to her concerning expected meta data.

**Comment by ecommarato** [comment]
There are two parts to this solution:
1.) Global "default" meta tags are available in the CMS under "Settings".  Changing these will change meta tags throughout the site
2.) Product-specific meta tags are available under each product, under the "Product Features" text area.  You can change these to override the global meta tags and insert tags specific to each product

**Comment by TOABridget** [comment]
Thank you for the information, however I'm still a bit confused as to where it is per product. I'm looking at the HX-5 in the CMS and the boxes appear to be blank. Am I looking in the wrong place for the product specific keywords?
![untitled-1](https://cloud.githubusercontent.com/assets/12281877/8932870/bc67bc78-350d-11e5-838d-749fdb3fe418.jpg)

**Comment by ecommarato** [comment]
That's correct!  The product meta tags are blank, which means they will show the global meta tags as default.  You can override the global meta tags by entering anything into the meta keywords and description for each product.

**Comment by TOABridget** [comment]
Is there any way to have both? Or is it not necessary? Or?

**Comment by ecommarato** [comment]
It should either be one or the other.  Google will favor pages that have distinct/unique meta data.

**Comment by rescobar2** [comment]
assigned to Dan

**Comment by rescobar2** [comment]
P3

**Comment by rescobar2** [comment]
Dan, don't think we want to go down this rabbit hole. There is meta data support but coming up desired meta is not something we should do in a vacuum. I would recommend as changing label to wont fix and not mess with meta data.

**Comment by chezshore** [comment]
Agreed. Please close this.


Best regards,

Dan Shore
Engineering/Product Manager
TOA Electronics, Inc.
Direct- 650-452-1208
Cell- 872-202-8274
dans@toaelectronics.com<mailto:dans@toaelectronics.com>

**Comment by rescobar2** [comment]
There are no current plans to edit Meta Data, closing
