### ISSUE TITLE
M-9000M2 rear photo is for A-9060DHM2

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Website#146]
Open this link.

http://www.toaelectronics.com/products/mixers/digital-mixers-processors/9000m2-digital-matrix-mix/m-9000m2

Click on Photo Rear
Result: Photo is of the A-9060DHM2

**Comment by rescobar2** [comment]
Still a Bug as of 9-22-16

**Comment by TOABridget** [comment]
Bob has me use this since day 1. Corporate uses the A-9060DHM2 rear photo as the rear photo of the M-9000M2 in all of their marketing materials and their website. Therefore one of the M-9000M2 specifically does not exist. One must be professionally taken.

**Comment by rescobar2** [comment]
Closing
