### ISSUE TITLE
TOA Global Web Site Image Missing

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Website#15]
Load: http://toaelectronics.com/support
Result: TOA Global Web Site Image Missing
![missing-image-014](https://cloud.githubusercontent.com/assets/6641267/7501753/607c220e-f3eb-11e4-8505-3c896512e395.jpg)

**Comment by ecommarato** [comment]
Fixed broken image!

**Comment by rescobar2** [comment]
verified as fixed closing
