### ISSUE TITLE
Links not opening to the correct file.

### ISSUE THREAD

**Issue by TOABridget** [westoforange/TOA-Website#158]
Hover over link in the text on this page:
http://toaelectronics.com/products/miscellaneous/zm-104a

Click to open the link and it does not open the file.

**Comment by rescobar2** [comment]
Text for hyperlink is: Impedance-to-Power Conversion Chart
http://toaelectronics.com/products/images/Impedance_Conversion_Chart.jpg

Still a bug, changed to P2

**Comment by TOABridget** [comment]
As explained to Erin in our meeting, any in line text links are not working. They do not work on any page. Erin will address this issue and fix.

**Comment by rescobar2** [comment]
Erin can you please review this.

**Comment by ecommarato** [comment]
Reviewing this issue

**Comment by ecommarato** [comment]
Link updated and fixed.
