### ISSUE TITLE
Upload M-864D 2.4.0 update

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Website#159]
Bridget,

Please replace 2.2.0 version with 2.4.0 version on this page:
http://www.toaelectronics.com/products/mixers/digital-mixers-processors/m-864d-digital-stereo-mixer/m-864d-digital-stereo-mix

Can you add text with software link to read "version 2.4.0

M-864D version 2.4.0 is here, file nto be uploaded "m-864d_us1e.zip"
T:\MARKETING\Personal Folders\Rick Escobar\Products\Mixers\M-864D\M-864D Software\M-864D version 2.4.0

**Comment by rescobar2** [comment]
File is corrupted and cannot be un-zipped

**Comment by rescobar2** [comment]
Cannot verify due to bug #163 Download is corrupted.

**Comment by TOABridget** [comment]
New file uploaded. Please check to verify.
