### ISSUE TITLE
http://toaelectronics.com/contact - East Coast Office links to FAQ page

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Website#16]
Load: http://toaelectronics.com/contact
Click on hyper link for:
East Coast Office
1 Harmon Plaza, Suite 602
Secaucus, NJ 07094
"This links to FAQ site"

![missing-image-015](https://cloud.githubusercontent.com/assets/6641267/7501840/18f3db2e-f3ec-11e4-9ec5-1b2d3d524366.jpg)

**Comment by ecommarato** [comment]
Fixed this link!

**Comment by rescobar2** [comment]
Link removed calling it fixed
