### ISSUE TITLE
Zipped files corrupted on download 

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Website#162]
Erin,

Bridget is using CYSM5 Dashboard, update media, select m-864d_us1e.zip, save, then publish
Result: m-864d_us1e.zip will be a corrupted zip on download and cannot be opened.

File is not corrupted on the server
http://www.toaelectronics.com/media/m-864d_us1e.zip

Here is a server path to the file
ftp://toawebadmin@216.98.109.197/httpdocs/media/m-864d_us1e.zip

Same problem with SPV-Speaker-Data-for-version 2.01.zip

http://www.toaelectronics.com/spv-data

**Comment by rescobar2** [comment]
Still a bug as of 9-22-16

**Comment by ecommarato** [comment]
Please send original files to my email address or attach them here

**Comment by rescobar2** [comment]
Erin, I cannot attach to the ticket, windows says the file is empty. Try these steps:
1. Go to http://www.toaelectronics.com/spv-data

This file can be downloaded from zip 
Placement Viewer
SR-C8.tsa

These two below create empty zip files. 
Data File
HS1200.tsa

SPV Speaker Data for version 2.01
SPV-Speaker-Data-for-version 2.01.zip

**Comment by ecommarato** [comment]
Thanks, will review

**Comment by rescobar2** [comment]
As of 3-6-18 worked for Dan, Rick will retest

**Comment by rescobar2** [comment]
assigned to Rick

**Comment by rescobar2** [comment]
Download to Speaker Data files now is to Data Library. This link is alive but not on any page. Calling bug invalid. To Dan to verify and close

**Comment by rescobar2** [comment]
Assigned to Dan to close

**Comment by chezshore** [comment]
Issue closed
