### ISSUE TITLE
Link to files may fail

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Website#169]
Open URL: http://www.toaelectronics.com/products/Voice-Evacuation-Systems/vm-3000-series-voice-evacuation-system/vm-3240va-voice-alarm-system-amplifier

Click on hyper link: Read this manual first before installing and operating.
Link URL: http://www.toaelectronics.com/products/Voice-Evacuation-Systems/media/vm3240e-ce_mx1e.pdf
Result: pdf is not open, link loads this view
![ev](https://cloud.githubusercontent.com/assets/6641267/18999388/25761412-86f2-11e6-82d6-b8d4b1f51fd6.jpg)

NOTE: Bridget says there are other examples where this happens

**Comment by ecommarato** [comment]
Please check on this and make sure the output is working now, I believe it has been resolved.

**Comment by rescobar2** [comment]
Verified as fixed, closing
