### ISSUE TITLE
http://toaelectronics.com/contact - broken Hyperlinks

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Website#17]
Load: http://toaelectronics.com/contact
Click on any of these Hyper Links Careers at TOA, Replacement Parts and Repair Information 
Result: 404 error page not found
![missing-image-016](https://cloud.githubusercontent.com/assets/6641267/7501895/9979a490-f3ec-11e4-8e4f-e2a9d34a48b2.jpg)

**Comment by ecommarato** [comment]
These links have been fixed!

**Comment by rescobar2** [comment]
verified as fixed 9-22-16
