### ISSUE TITLE
Files not appearing in backend

### ISSUE THREAD

**Issue by TOABridget** [westoforange/TOA-Website#171]
File already exists on the cloud. Go to product page to add file. Search brings no results. Manually looking also does not find it. Where are they disappearing to? Try to find file in the 'media' folder:
'IR-700_Wireless_System_A&E_Specification.pdf'

**Comment by ecommarato** [comment]
Were these ever found?

**Comment by TOABridget** [comment]
Nope, still lost, still not appearing.

**Comment by ecommarato** [comment]
Can you send me the original PDF file?

**Comment by ecommarato** [comment]
I wasn't able to figure out why the files aren't showing up, but I have a stopgap solution for you:
You can paste in the file's location starting with /media
I did this for the A&E specs for the IR-700, so the full media file is "/media/IR-700_Wireless_System_A&E_Specification.pdf"

See http://toaelectronics.com/adm1n3907/mod_products_a.php?action=edit_product&prodid=478#media

**Comment by rescobar2** [comment]
assigned to Rick

**Comment by rescobar2** [comment]
I was able to add firmware 2.74 for VM-3240VA and download from web site. Not sure what Bridget's issue was. I changed to invalid and will create a new bug if I encounter this. To Dan, recommend closing.

**Comment by chezshore** [comment]
After investigation, this is a non-issue. Issue closed
