### ISSUE TITLE
EV-700 firmware and software 1.3 is outdated

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Website#173]
EV-700 firmware and software 1.3 is outdated
http://www.toaelectronics.com/products/audio-signal-processors/digital-announcer

Please replace with 1.4 firmware and software versions from 
http://www.toa-products.com/international/search.php?mode=VIEW&alpha=&renew=&keiretsu=&data_type=&hinban=EV-700

Please use all documentation manuals etc from the Data Library link

**Comment by TOABridget** [comment]
It has been updated please check then close this bug.

**Comment by rescobar2** [comment]
Verified as fixed, closing
