### ISSUE TITLE
Add Documents for NX-300

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Website#174]
Please add these downloads to the NX-300 product page
http://www.toaelectronics.com/products/network-audio-adapters/nx-300-series-network-audio

Please add all files from this NX-100 [Data Library](http://www.toa-products.com/international/detail.php?h=NX-300+W&keiretsu=&alpha=&renew=&data_type=) page:

Also add this text please:
"The latest NX-300 firmware version is 2.0.1(update:2016/10/7). The software version is 2.0.0(upload:2016/9/23)."

**Comment by TOABridget** [comment]
Please review, files have been uploaded.

**Comment by rescobar2** [comment]
Verified as fixed, closing.
