### ISSUE TITLE
Search not finding BG-235 in test

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Website#176]
From toaelectronics.com search for "bg235"
Result: No result found
Expected: Should have found items on this page
http://www.toaelectronics.com/products/Amplifiers/bg-200-series-power-amplifiers
NOTE: If I search for bg-235 is will find  
BG-235 CAD and BG-235 Spec Sheet
NOTE: Also found same type of behavior searching for  a724 vs a-724. I would expect to find other examples such as this.

**Comment by rescobar2** [comment]
Please see examples of search results
[Search-issues.pdf](https://github.com/westoforange/TOA-Website/files/865678/Search-issues.pdf)

**Comment by ecommarato** [comment]
Fixed

**Comment by rescobar2** [comment]
Verified as fixed, closing
