### ISSUE TITLE
Cannot close an opened image

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Website#177]
Load http://www.toaelectronics.com/products/mixers/digital-mixers-processors/d-2000-digital-mixing-system/d-2008sp

Click on any image of the D-901
Result: Cannot close window, must use back button to get out.

Appears to be a global issue

**Comment by rescobar2** [comment]
Hi Erin,

I understand this bug was fixed but for me it was only after I flushed my cache this morning.

**Comment by ecommarato** [comment]
Correct, the changes to the stylesheet that fixed this bug may have been temporarily cached.
