### ISSUE TITLE
YouTube videos not playing

### ISSUE THREAD

**Issue by TOABridget** [westoforange/TOA-Website#178]
http://www.toaelectronics.com/products/Amplifiers/digital-mixer-amplifier

This video plays in YouTube but it does not play on our website. What's the problem?

**Comment by ecommarato** [comment]
What is the full URL of the video? Looks like the youtube ID is shorter than normal, so I wonder if some part of the ID is missing?

**Comment by ecommarato** [comment]
Can you send me the full video URL?

**Comment by TOABridget** [comment]
https://www.youtube.com/watch?v=iO5h73a-97w&list=PLfPAMicTSQu0sxIa_ZdwIcdlX7cj6Ky3I

**Comment by TOABridget** [comment]
https://www.youtube.com/watch?v=iO5h73a-97w&list=PLfPAMicTSQu0sxIa_ZdwIcdlX7cj6Ky3I

**Comment by ecommarato** [comment]
Got it! It was missing a few characters from the full URL

**Comment by TOABridget** [comment]
Working great!
