### ISSUE TITLE
http://toaelectronics.com/support - ZM-104 link broken

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Website#18]
Load: http://toaelectronics.com/support 
Click on ZM-104 link broken hyper link
Result: Page not found

Click on hyper link word "here:
To see a list of our discontinued products, please click here
Result: page not found
![missing-image-017](https://cloud.githubusercontent.com/assets/6641267/7502031/cffd68c0-f3ed-11e4-81cc-fb479095fec0.jpg)

**Comment by TOABridget** [comment]
I got this

**Comment by TOABridget** [comment]
Links fixed.
