### ISSUE TITLE
Search for PE-304 is coming up with invalid results

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Website#180]
Start from toaelectronics.com 
In the Search field enter PE-304
Result: There also be PE-604 products and information found in the result
For this first product listed:
TOA Product | Pendant Speaker (UL1480UUMW rated)
PE-304-604BU-WU
Click the first Installation Manual link:
http://www.toaelectronics.com/media/manuals/bs-680u_mi1e.pdf
The manual of for the bs-680
Expected: http://www.toaelectronics.com/media/manuals/pe-304bu_mt1e.pdf

**Comment by ecommarato** [comment]
Removed an invalid link between PE-304 and the Installation manual

**Comment by rescobar2** [comment]
Verified as fixed, closing
