### ISSUE TITLE
Cursor focus remains in the search field

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Website#182]
Cursor focus remains in the search field

**Comment by rescobar2** [comment]
Go to new search engine: http://toaelectronics.com/toa-faq-new
search for EV700
After result press the enter key
Result: A new query will result in all FAQ's being found. See this documented example.
[bug 182 Search.pdf](https://github.com/westoforange/TOA-Website/files/1065010/bug.182.Search.pdf)

**Comment by ecommarato** [comment]
Fixed in new search http://toaelectronics.com/toa-faq-new

**Comment by rescobar2** [comment]
Verified as fixed, closed
