### ISSUE TITLE
Searching for just Category results in entire database being found

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Website#183]
Go to the current live FAQ link
http://www.toaelectronics.com/toa-faq

For Category = select a product line from the drop down list
For Subcategory = Any
Click the Search button
Result: All FAQ's in the database will be found
Expected: Only FAQ's in searched Category should have been found

**Comment by ecommarato** [comment]
Fixed as part of the new FAQ search
http://toaelectronics.com/toa-faq-new

**Comment by rescobar2** [comment]
Verified as fixed, closed
