### ISSUE TITLE
PDF files loading blank

### ISSUE THREAD

**Issue by TOABridget** [westoforange/TOA-Website#184]
I've re-uploaded files again and still the same result.
Files are downloading blank.
How to fix?

http://toaelectronics.com/media/specs/w906a_sa1e.pdf
http://toaelectronics.com/media/specs/w912a_sa1e.pdf

**Comment by ecommarato** [comment]
I tried downloading and opening these files but get a message that the file is corrupt. Can you email me the original PDFs?

**Comment by ecommarato** [comment]
Changed a few settings and re-uploaded, files seem to be working now!

**Comment by rescobar2** [comment]
Verified as fixed, closing
