### ISSUE TITLE
Search Again boarder exceeds page margin on opened result

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Website#185]
From FAQ search for any topic and click on link that takes you to the FAQ
Result: The Search Again boarder exceeds the right hand side page margin.
Note: Reproduced in IE 11 and Chrome Version 59.0.3071.115 (Official Build) (64-bit)

**Comment by ecommarato** [comment]
Fixed styles for search again form

**Comment by rescobar2** [comment]
Verified as fixed, closing
