### ISSUE TITLE
http://toaelectronics.com/contact# - additional link issues

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Website#19]
Load: http://toaelectronics.com/contact#

Click Here for Free Design Support

Contact Us links not hyperlinked
Sales Managers 
Repair Information
Customer Support

![missing-image-018](https://cloud.githubusercontent.com/assets/6641267/7502235/4f1817a8-f3ef-11e4-8ea6-9d20137f2298.jpg)

**Comment by rescobar2** [comment]
Add Under Contact US frame / Customer Support Hyperlink and another issue

**Comment by ecommarato** [comment]
Please send the link URLs and email addresses the links should point to.

**Comment by TOABridget** [comment]
I can't seem to find this in the back-end to edit myself, please help!
Sales Managers: http://www.toaelectronics.com/sales
Repair Information: http://www.toaelectronics.com/service
Customer Support: http://www.toaelectronics.com/customer-service

**Comment by ecommarato** [comment]
This is located in two sections:
Sidebar: Edit under Contact Us Sidebar.. I edited these links already so you don't have to do anything.

The contact page is split into 4 content blocks.  The one containing the Free Design box is called Contact 2.  I didn't know what the Free Design Support link should go to though so I didn't edit this block.

**Comment by TOABridget** [comment]
Got it, thanks!
