### ISSUE TITLE
ZM-104 shown on wrong page

### ISSUE THREAD

**Issue by chezshore** [westoforange/TOA-Website#194]
ZM-104 is shown on http://www.toaelectronics.com/products/Pro-Audio-Speakers

Please move to http://www.toaelectronics.com/products/PA-Speakers

**Comment by rescobar2** [comment]
assigned to Rick

**Comment by rescobar2** [comment]
Fixed. Dan after verified then make comment and push Close and comment button

**Comment by rescobar2** [comment]
Fixed. Dan after verified then make comment and push Close and comment button

**Comment by chezshore** [comment]
Verified
