### ISSUE TITLE
Product names are wrong on VM-3000 landing page

### ISSUE THREAD

**Issue by chezshore** [westoforange/TOA-Website#195]
http://www.toaelectronics.com/products/Voice-Evacuation-Systems/vm-3000-series-voice-evacuation-system

Change VM-3240VA to VM-3240VA AMQ
Change VM-3240E to VM-3240E AMQ
Change VX-2000DS to VX-2000DS AMQ
Change RM-200M S to RM-200MPS

**Comment by rescobar2** [comment]
Assigned to Dan

**Comment by rescobar2** [comment]
Add AMQ after each name, assigned to Rick

**Comment by rescobar2** [comment]
Fixed to Dan to verify

**Comment by chezshore** [comment]
Verified.


Best regards,

Dan Shore
Engineering/Product Manager
TOA Electronics, Inc.
Direct- 650-452-1208
Cell- 872-202-8274
dans@toaelectronics.com<mailto:dans@toaelectronics.com>

**Comment by chezshore** [comment]
Verified. Issue closed
