### ISSUE TITLE
Change VM-3000 firmware version back to 2.74

### ISSUE THREAD

**Issue by chezshore** [westoforange/TOA-Website#197]
On this page-
http://www.toaelectronics.com/products/Voice-Evacuation-Systems/vm-3000-series-voice-evacuation-system/vm-3240va-voice-alarm-system-amplifier

Remove Firmware v3.0 and replace with Firmware v2.74+

v3.0 is for Germany and is not UL approved

**Comment by rescobar2** [comment]
Dan to you to verify fixed

**Comment by chezshore** [comment]
Verified. Issue closed
