### ISSUE TITLE
VM-3240VA change Software version to 2.0

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Website#200]
The current VM-3240VA software version is 3.0 on web site. Will change to ver 2.0. Add ver number to download text

"http://toaelectronics.com/products/Voice-Evacuation-Systems/vm-3000-series-voice-evacuation-system/vm-3240va-voice-alarm-system-amplifier"

**Comment by rescobar2** [comment]
Dan please verify and close if fixed.

**Comment by chezshore** [comment]
Verified. Closed this issue.
