### ISSUE TITLE
Add firmware verion text to N-SP80VS1 download link

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Website#201]
http://toaelectronics.com/products/intercom-systems/sip-intercom-series/outdoorindoor-sip-video-door-station

Download link just reads firmware. I'm going to add text ver 21.192.2.11

**Comment by rescobar2** [comment]
Assigned to Dan to verify as fixed

**Comment by chezshore** [comment]
Verified. Issue closed
