### ISSUE TITLE
Correct all issues for software download

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Website#207]
http://toaelectronics.com/products/audio-signal-processors/dp-sp3-digital-processor
Current software version is 2.1.1 from Data Library

Remove text:
Software Update
08/07/2013 - Ver. 2.0.0
Addition of New Function - Capability of protocol control
Bug Fix - Polarity is not changed in synchronization with X-over grouping change.

Current download is 2.1.0, correct this at FTP side

Change software download link text to 2.1.1

**Comment by rescobar2** [comment]
To Dan to verify as fixed

**Comment by chezshore** [comment]
Verified. Issue closed
