### ISSUE TITLE
Remove links to Q-N8540WP

### ISSUE THREAD

**Issue by chezshore** [westoforange/TOA-Website#213]
IP SYSTEMS 6

On the following pages-
http://www.toaelectronics.com/products/intercom-systems/ip-stations/n-8600ms
http://www.toaelectronics.com/products/intercom-systems/ip-stations/n-8640ds
http://www.toaelectronics.com/products/intercom-systems/ip-stations/n-8650ds
http://www.toaelectronics.com/products/intercom-systems/ip-stations/n-8640sb

Remove the following text and link-

•	Outdoor IP Substation 
•	link to http://www.toaelectronics.com/products/q-n8540wp

**Comment by chezshore** [comment]
To Rick for verification

**Comment by rescobar2** [comment]
Verified as fixed, closing
