### ISSUE TITLE
Correction to N-8640DS

### ISSUE THREAD

**Issue by chezshore** [westoforange/TOA-Website#214]
IP STATIONS 7

On these pages-
http://www.toaelectronics.com/products/intercom-systems/ip-stations/n-8640ds
http://www.toaelectronics.com/products/intercom-systems/ip-stations/n-8640sb

Remove this text-

Chemical resistant for use in industrial/harsh environments

**Comment by chezshore** [comment]
To Rick for verification

**Comment by rescobar2** [comment]
Verified as fixed, closing
