### ISSUE TITLE
Product Mix for Markets

### ISSUE THREAD

**Issue by bobtoa602** [westoforange/TOA-Website#23]
All Markets link to the same product page, which appears to be an arbitrary mix of products (not related to that market). This is not representative of the category map that was submitted for the Markets section.

**Comment by ecommarato** [comment]
Currently in progress.  Icons on homepage have been updated and the following pages complete:
Corporate
Education
Healthcare

**Comment by ecommarato** [comment]
All pages complete with exception of the resources links and some products that were not found on the site (these are indicated with a blank square, no image, just the product id)

**Comment by rescobar2** [comment]
Bridget please review and close if fixed
