### ISSUE TITLE
Right Side Link Bar 

### ISSUE THREAD

**Issue by bobtoa602** [westoforange/TOA-Website#25]
Still looks confusing. Needs clearer delineation between each box.

**Comment by ecommarato** [comment]
Is this a design-related issue?  Which box needs to be more defined?

**Comment by TOABridget** [comment]
How about a little faded line between with a little more space between? Could that work? Is that difficult to do?

**Comment by ecommarato** [comment]
I added spacing between each product category.  This is also part of another ticket, so I'm closing this one.
