### ISSUE TITLE
Amplifier Sub-Categories

### ISSUE THREAD

**Issue by bobtoa602** [westoforange/TOA-Website#26]
700, A-2000, BG-200 & BG-2000 should be displayed as sub categories in the Amplifier Product section. "Integrated Mixer-amps" is confusing and makes it harder to find these models.

**Comment by TOABridget** [comment]
@ecommarato The products in the Integrated Mixer / Amplifiers category need to be their own each individual category. Is there an easy way to do this other than manually?
