### ISSUE TITLE
FAQ on Corp site fails for multiple keyword search 

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Website#31]
Open FAQ on toaelectronics.com
Search any phase found in a FAQ such as "Ticking Sound"
Result: No record will be found
Note: if you enter a single word of "ticking" or "sound" it will be found

**Comment by rescobar2** [comment]
to Erin

**Comment by ecommarato** [comment]
This issue should be resolved now.

**Comment by rescobar2** [comment]
verified as fixed, closing. RE
