### ISSUE TITLE
This is sample data being downloaded on the server

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Website#33]
From http://toa.webdevstaging.com/manuals add M-900MK2.pdf  
Click on My Downloads
Send to your email address
Open the downloaded zipped folder
Result:
Download and open the zipped folder
Result: Folder is SampleData and contains a brochure on furniture 
NOTE: The info@toaelectronics.com email sends with an invalid 404 link

**Comment by ecommarato** [comment]
The link in original ticket is from the development server.  I tried to duplicate bug on live server and found everything to work as expected.  Did not see furniture brochure and download link worked.  Zip file contained the correct pdf.

**Comment by rescobar2** [comment]
See attached test case results for failed downloads
[My_Downloads_Test_Matrix.pdf](https://github.com/westoforange/TOA2014/files/404/My_Downloads_Test_Matrix.pdf)

**Comment by ecommarato** [comment]
Fixed!

**Comment by rescobar2** [comment]
verified as fixed 7-28-15
