### ISSUE TITLE
N-8000 Downloaded 2.02 of Software

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Website#39]
Example:

Go to http://toa.webdevstaging.com/products/intercom-systems/system-exchanges/n-8000rs
Download Firmware and software

Result:
N-8000 Downloaded 2.02 of Software and firmware is 2.10 
Software should be 4.1.0 and firmware should be 4.1
NOTE: All N-8000 products will need to be verified for correct software and firmware versions

**Comment by TOABridget** [comment]
I do not see a 2.02. Please help.
![untitled-1](https://cloud.githubusercontent.com/assets/12281877/7635375/955558e4-fa2e-11e4-841a-aef06c7b2f54.jpg)
