### ISSUE TITLE
Social Media Links leave TOA site

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Website#4]
Click on any of the social media links
Result: Leave toaelectronics.com to new site
Expected: opens a new page
NOTE: Best to ask Bridget how she wants this to work.

**Comment by ecommarato** [comment]
Bridget has already stated her preference to open all external links in a new tab/window.

**Comment by ecommarato** [comment]
Social links now open in new tab

**Comment by bobtoa602** [comment]
Verified as fixed-Opens new tab
