### ISSUE TITLE
Software and firmware downloads for NX-100 incorrect

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Website#40]
Go to:
http://toa.webdevstaging.com/products/network-audio-adapters/nx-100-series-network-audio
Download firmware and software 
Result: Firmware is 2.15 and software is 2.18
Expected: Should both be 2.20

**Comment by TOABridget** [comment]
I was unaware there was an update - please let me know immediately in the future and I can get all files like this updated immediately.
