### ISSUE TITLE
My Downloads failing for more than one item

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Website#41]
Add 2 items to My Downloads
Download and attempt to open
Result: Error msg that zipped file is invalid

**Comment by ecommarato** [comment]
Appears to be working as expected now.

**Comment by rescobar2** [comment]
Currently MyDownloads is making empty .zip files

Also the emailed link is invalid 404 error

**Comment by ecommarato** [comment]
All fixed!

**Comment by rescobar2** [comment]
verified as fixed 7-28-15
