### ISSUE TITLE
Missing and incorrect link for VM-3240VA

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Website#42]
Load URL:
"http://toa.webdevstaging.com/products/Voice-Evacuation-Systems/vm-3000-series-voice-evacuation-system/vm-3240va-voice-alarm-system-amplifier"

Link for "Read this manual...." just returns to Products Home Page:
http://toa.webdevstaging.com/products/Voice-Evacuation-Systems/media/vm3240e-ce_mt1e.pdf

Missing image on page

![image-020](https://cloud.githubusercontent.com/assets/6641267/7601546/5abe82f4-f8cc-11e4-8b36-a60711ddb6a2.jpg)

**Comment by TOABridget** [comment]
Image moved to image gallery to appear properly. Link fixed.
