### ISSUE TITLE
New Product Media

### ISSUE THREAD

**Issue by TOABridget** [westoforange/TOA-Website#46]
Went to make a new product page in the 9000M2 category and it pulled in media randomly from I have no idea where when I created the page initially.

**Comment by ecommarato** [comment]
This seems to be related to the missing Mixers.  Since there was a gap in the database, it may have tried to fill it in with what it thought was the mixer products.  Let me know if this happens again, but I'm reasonably sure it has been cleared up.

**Comment by TOABridget** [comment]
Will do, thanks!
