### ISSUE TITLE
File size

### ISSUE THREAD

**Issue by TOABridget** [westoforange/TOA-Website#50]
Some software and firmware files need to be updated, however, they are larger than 10MB. File upload size needs to be changed to allow at least 15MB.

**Comment by ecommarato** [comment]
For larger files, I would recommend using Filezilla FTP client to upload.  However, we can also open a ticket with DeviceNet to increase the file size for uploading.

**Comment by TOABridget** [comment]
I'm having trouble using FileZilla. It will not allow me to upload anything. If I had this option, I would certainly use FileZilla to upload everything! How can we fix this?

**Comment by ecommarato** [comment]
I responded to Toshimi's latest email asking her to allow uploads via FTP.

**Comment by ecommarato** [comment]
Does FTP work for you now Bridget?
