### ISSUE TITLE
Timezone needs to be set in php.ini 

### ISSUE THREAD

**Issue by ecommarato** [westoforange/TOA-Website#52]
We started seeing the following error in the error logs today: 
[Fri May 15 06:17:48 2015] [error] [client 96.247.155.150] PHP Warning:  date( It is not safe to rely on the system's timezone settings. You are _required_ to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected 'America/Los_Angeles' for 'PDT/-7.0/DST' instead in /var/www/vhosts/toaelectronics.com/httpdocs/includes/functions.php on line 27, referer: http://www.toaelectronics.com/products/mixers/digital-mixers-processors/m-864d-digital-stereo-mixer

Can DeviceNet add the timezone to the php.ini file?

**Comment by rescobar2** [comment]
Erin if this no longer a bug please close
