### ISSUE TITLE
Cannot separate states in map

### ISSUE THREAD

**Issue by TOABridget** [westoforange/TOA-Website#55]
The region of AZ and NM need to be separate. I tried to delete NM but it won't let me. Help!

**Comment by TOABridget** [comment]
MO is also missing from the NE, KS, IA, MO, IL (SOUTH) group.

**Comment by ecommarato** [comment]
I added NM as a separate region in dark blue, then added a new Region for it in the CMS (called NEW MEXICO).  It's ready for content!

**Comment by TOABridget** [comment]
Fantastic, thanks!
