### ISSUE TITLE
Missing Module Tones from Site

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Website#56]
Go to TOA TCC site:
http://www.toacanada.com/shop/en-and-88-2/900-series-mixer-power-amplifiers/

At the bottom of the page are all the 900 module tones (wav files) that used to be on TOA TEI site.

These need to be added as downloads

**Comment by TOABridget** [comment]
I cannot add them because the file type is not accepted to upload.

**Comment by TOABridget** [comment]
Can we have a blank icon or a placeholder of some kind for a WAV file type? The file name is repeated 2x and it looks confusing.

**Comment by ecommarato** [comment]
WAV files can now be added - do we need a separate category for tones under Support?

**Comment by TOABridget** [comment]
Yes, that would be fantastic!

**Comment by ecommarato** [comment]
Added "Tones" to support menu
