### ISSUE TITLE
Add "Integrated Mixer-Amp" Category in Main Product List

### ISSUE THREAD

**Issue by bobtoa602** [westoforange/TOA-Website#57]
Assign all mixer amps: BG-200/2000, 700, 900MkII, WB-900, 9000M2, A-2000 to this category. All others: DA Series, Micro, BA-200, P-900MkII, P-9000 to "Amplifiers"

**Comment by TOABridget** [comment]
This is contradictory to Issue #26 where you state "700, A-2000, BG-200 & BG-2000 should be displayed as sub categories in the Amplifier Product section. "Integrated Mixer-amps" is confusing and makes it harder to find these models." That issue has been settled and closed. Now you want to revert back? Makes no sense.

**Comment by rescobar2** [comment]
Bridget please review and close if fixed
