### ISSUE TITLE
Missing image from http://toaelectronics.com/military

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Website#6]
Open http://toaelectronics.com/military
Result: Missing large image
![missing-image-005](https://cloud.githubusercontent.com/assets/6641267/7501173/1a578556-f3e7-11e4-9165-096bee62d9a8.jpg)

**Comment by ecommarato** [comment]
Content copied into military page

**Comment by bobtoa602** [comment]
Same incorrect product mix page as other Markets
