### ISSUE TITLE
Paging Systems Icon

### ISSUE THREAD

**Issue by bobtoa602** [westoforange/TOA-Website#69]
Should change to "Paging Accessories" and may be shown in both Power Amplifier & Integrated Mixer-Amplifier categories. IB-9012 -should delete description of main system on this page.

**Comment by TOABridget** [comment]
Paging Systems? I don't see where that is. I see Multi-Zone Paging Systems. Please clarify.

**Comment by rescobar2** [comment]
Bridget please review and if fixed close
