### ISSUE TITLE
Trantec image missing form http://toaelectronics.com/metro

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Website#7]
Open http://toaelectronics.com/metro
Result: Trantech image missing from blank white box
![missing-image-006](https://cloud.githubusercontent.com/assets/6641267/7501218/5ad64414-f3e7-11e4-9c91-7df42e42e794.jpg)

**Comment by ecommarato** [comment]
This appears to be another content question for Bridget

**Comment by ecommarato** [comment]
Page has since been updated with new content.
