### ISSUE TITLE
Micro Amps

### ISSUE THREAD

**Issue by bobtoa602** [westoforange/TOA-Website#71]
Move to Power Amplifiers. Change position of categories (accessories below)

**Comment by TOABridget** [comment]
I cannot change the position of the categories, that it something @ecommarato has to change in the code.

**Comment by ecommarato** [comment]
Which category needs to be changed?

**Comment by TOABridget** [comment]
@bobtoa602 Please help Erin, I do not know exactly what you want.

**Comment by rescobar2** [comment]
Bridget please review and if fixed close
