### ISSUE TITLE
DA Series Power Amplifiers

### ISSUE THREAD

**Issue by bobtoa602** [westoforange/TOA-Website#73]
Move to Power Amplifiers. Does not need intermediate page. No images on sub-category page for DA-250DH, DA-250FH & DA-500F-HL. Shows model numbers twice (top line should be description).  Needs description on model pages. Most photo links missing. No back panel images. Ones there are low rez. No photo scroll.

**Comment by TOABridget** [comment]
I don't have images of both front and back for all, will need to download from TPW. Everything else should be good for now.

**Comment by rescobar2** [comment]
load:
http://www.toaelectronics.com/products/Amplifiers/power-amplifier/da-series-multi-channel-digital-amplifiers/da-250fh
Result: Scroll image for DA-250FH Rear is missing

**Comment by TOABridget** [comment]
We need to ask @ecommarato why it's missing since the image is loaded.

**Comment by ecommarato** [comment]
Appears to have been fixed in an earlier update
