### ISSUE TITLE
N-8000 software and firmware out dated

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Website#75]
N-8000 software and firmware out dated

Correct current versions have been downloaded and are located here:
T:\MARKETING\Personal Folders\Rick Escobar\Products\Intercom\000-For Web SIte

**Comment by TOABridget** [comment]
Yes, I understand. However, I keep asking for assistance on which exact products need this software. I do not know which ones need it and which ones do not. I need help on this and then I can close this issue.
