### ISSUE TITLE
Images in slideshow

### ISSUE THREAD

**Issue by ecommarato** [westoforange/TOA-Website#79]
Images in slideshow are sometimes too large

**Comment by ecommarato** [comment]
Should be fixed on all pages now.  Let me know if you see any more problems with the slideshow on product pages.

**Comment by TOABridget** [comment]
Please see this page, the images in the slideshow don't seem to fit nicely.
http://toaelectronics.com/products/Pro-Audio-Speakers/sr-mf1-mechanically-steerable-line-array-speaker-s

**Comment by ecommarato** [comment]
This should be fixed now.  Take a look and let me know!

**Comment by rescobar2** [comment]
Bridget please review and close if fixed
