### ISSUE TITLE
Trantec image missing from http://toaelectronics.com/mall

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Website#8]
Load http://toaelectronics.com/mall
Result: Trantec image missing
![missing-image-007](https://cloud.githubusercontent.com/assets/6641267/7501268/a8a4efce-f3e7-11e4-852b-3e3f3b86fbe8.jpg)

**Comment by rescobar2** [comment]
Trantec image missing form all the Market pages

**Comment by ecommarato** [comment]
Page has since been updated with new content.
