### ISSUE TITLE
Product Part ID hyphens

### ISSUE THREAD

**Issue by TOABridget** [westoforange/TOA-Website#80]
The box where you enter the product part ID is randomly putting in hyphens or dashes when edited and cannot be deleted.

**Comment by ecommarato** [comment]
Which product(s) are doing this?

**Comment by TOABridget** [comment]
In the Amplifier section: BG-2000-Series, BG-200-Series, and BA-200-Series. The system put a dash between the part and 'Series' and there should be no dash there. I know there are more, that's what I can remember as of now.

**Comment by ecommarato** [comment]
The system will no longer force a dash in between words in the product ID
