### ISSUE TITLE
Unable to locate where to upload...

### ISSUE THREAD

**Issue by TOABridget** [westoforange/TOA-Website#81]
Now that our file upload has increased, I need to upload new files of both our USA and Spanish catalogs - but I can't quite figure out where....

**Comment by ecommarato** [comment]
Both are under the /media directory

**Comment by TOABridget** [comment]
Media directory where? How do I get to that link for this directory? FTP still isn't working for me so I'm a little lost. I'm so use to code that I can't find the hyperlink text to edit.

**Comment by ecommarato** [comment]
Ah! Ok, so you can go to any content page and click the Image icon to open the media library.  Then, click Media.  The links for the catalogs are hard-coded, so you will need to DELETE the existing catalogs, then re-upload them using the same file names.  

I will remind DeviceNet to allow FTP access to /media and /images again.
![screen-shot-2015-06-02-at-9 25](https://cloud.githubusercontent.com/assets/6640152/7936458/2f3b8776-0907-11e5-9fb6-66e254b23dbe.jpg)

**Comment by TOABridget** [comment]
Noted - delete before upload!
