### ISSUE TITLE
SR-D8 software version out of date

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Website#82]
SR-D8 software download is outdated
http://www.toaelectronics.com/products/Pro-Audio-Speakers/sr-d8-active-line-array-speaker-system

Please replace with srd8_us1e.zip 1.1.0 from: 
T:\MARKETING\Personal Folders\Rick Escobar\Products\Pro Audio Speakers\SR-D8\software 1.1.0

**Comment by TOABridget** [comment]
Updated.
