### ISSUE TITLE
New Homepage Box Needed

### ISSUE THREAD

**Issue by TOABridget** [westoforange/TOA-Website#84]
Can I create a new box thing on the homepage? Or that something @ecommarato you need to do?

**Comment by ecommarato** [comment]
This can be done in the CMS, using the sidebar module.  There are 3 sidebars for the frontpage: Frontpage left, frontpage middle and frontpage right.  Select the one you wish to edit and then, under "Add New Item to Sidebar" select Text Area.  Use the editor to create your content.
