### ISSUE TITLE
Markets Pages Formatting

### ISSUE THREAD

**Issue by TOABridget** [westoforange/TOA-Website#87]
We're adding to the Markets pages and the formatting seems a bit off. Is there a secret I need to know so I can make it all look uniform and pretty?
http://www.toaelectronics.com/conference

**Comment by ecommarato** [comment]
Regarding the links that are hanging out of the table cells: The class "caption", applied to the <td> element will give the nice grey background appearance.  Open the page in HTML view to see that the TD cells with the class of "caption" are the ones that are styled with the grey bg and white text.  

The code should look like this: <td class="caption" style="text-align: center;"><a href="http://www.toaelectronics.com/products/conference-systems/ts-770-series/ts-770-series-portable-conference-system">TS-770 Series</a></td>

Let me know if I can help in any way - I'm sure this is as clear as mud :)

**Comment by rescobar2** [comment]
Bridget please and close if fixed
