### ISSUE TITLE
Right side bar links leave site from home page

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Website#9]
Load home page
See image for links that leave TOA site
![missing-image-008](https://cloud.githubusercontent.com/assets/6641267/7501394/633b0648-f3e8-11e4-8dcd-d336216b33af.jpg)

**Comment by ecommarato** [comment]
I believe that is the desired outcome - Bridget set the links up through the CMS.

**Comment by bobtoa602** [comment]
Use as is
