### ISSUE TITLE
Add Data Library Link to Products Page

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Website#92]
Request to add Data Library to Products Page
http://www.toaelectronics.com/products

**Comment by TOABridget** [comment]
Please discuss this with @bobtoa602, I know he was opposed to this.

**Comment by rescobar2** [comment]
By PSG request can we add the DataLibrary to the Product page?

**Comment by rescobar2** [comment]
For Bridegt comment

**Comment by TOABridget** [comment]
I think we can, I'm just not sure how to do that.

**Comment by rescobar2** [comment]
Use as is, closing
