### ISSUE TITLE
Cannot get zipped files for speaker data

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Website#93]
Go to http://www.toaelectronics.com/ease-data
 Locate this file and download it. Since My Downloads doesn’t work use Right click and save as .zip
SPV Speaker Data for version 2.01
SPV-Speaker-Data-for-version 2.01.zip   H

Result: The zipped file cannot be opened

**Comment by ecommarato** [comment]
Rick, I see the problem and it appears the file is bad - do you or Bridget have a copy of this file we may upload?

**Comment by rescobar2** [comment]
Hi Erin, here is a link to the software program and data
"http://www.toa-products.com/international/detail.php?h=XZS_SPV&keiretsu=&alpha=&renew=&data_type=speaker-e"

**Comment by rescobar2** [comment]
Bridget all the SPV data is missing only the software is there.
http://www.toaelectronics.com/products/PA-Speakers/speaker-placement-viewer-software

here is a link to the software program and data
"http://www.toa-products.com/international/detail.php?h=XZS_SPV&keiretsu=&alpha=&renew=&data_type=speaker-e"

**Comment by TOABridget** [comment]
SPV data lives here per Bob's request. http://www.toaelectronics.com/spv-data
We can put a note on the page that the data is there.
Please advise.

**Comment by rescobar2** [comment]
Please add a link to http://www.toaelectronics.com/spv-data

**Comment by rescobar2** [comment]
Verified as fixed
