### ISSUE TITLE
Separate SPV and Ease Data

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Website#94]
Load this page
http://www.toaelectronics.com/products/PA-Speakers

This is a link to the Speaker Placement Viewer Software (SPV) page
http://www.toaelectronics.com/products/PA-Speakers/speaker-placement-viewer-software

This is a link to the EASE page
http://www.toaelectronics.com/products/PA-Speakers/ease-focus-software

Open the Speaker Placement Viewer Software (SPV) page
Then the hyperlink "Click here for a list of applicable speaker models" This loads http://www.toaelectronics.com/ease-data which is mix of SPV and EASE date files.

There should be two URLS

This would contain only the EASE Data file and would be available from the EASE page
http://www.toaelectronics.com/ease-data

This would be only the SPV data file, they all end .tsa or have SPV in the file name
http://www.toaelectronics.com/SPV

**Comment by ecommarato** [comment]
Added a new category for SPV data and moved .tsa and SPV files into it.

**Comment by rescobar2** [comment]
Verified, closing
