### ISSUE TITLE
Missing EASE Focus Software Page

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Website#95]
Go to: http://www.toaelectronics.com/products/PA-Speakers
Result: Image for EASE Focus Software is missing

**Comment by TOABridget** [comment]
Please provide me with an image of it.

**Comment by rescobar2** [comment]
Here is the Ease Focus Logo

![focus_ii_splash_200](https://cloud.githubusercontent.com/assets/6641267/8413386/f3d224e4-1e44-11e5-9101-1bb385fa52cd.png)

**Comment by TOABridget** [comment]
Not able to upload!!!!

**Comment by rescobar2** [comment]
Not fixed on this page, re-opening
