### ISSUE TITLE
Horn Array Speaker

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Website#98]
Load: http://www.toaelectronics.com/products/Voice-Evacuation-Systems/horn-array-speaker

Sliding images not displaying and run together text.

![horn array speaker](https://cloud.githubusercontent.com/assets/6641267/8340489/b24045da-1a73-11e5-9b66-bacb59ee2996.jpg)

**Comment by TOABridget** [comment]
This is something @ecommarato needs to look into for us.

**Comment by ecommarato** [comment]
It looks like the slider has space for only one line of text.  If I increase the height, it will increase the height across the board, site-wide, and this may end up making the rest of the sliders look like there's a large gap at the bottom.  Can the caption text be edited so it all fits on a single line?

**Comment by rescobar2** [comment]
still a bug 9-22-16

**Comment by rescobar2** [comment]
verified as fixed, closing
