### ISSUE TITLE
Missing images for DA Series Products

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Website#99]
The following pages are missing product image in lower left

http://www.toaelectronics.com/products/Amplifiers/power-amplifier/da-series-multi-channel-digital-amplifiers/da-250d
http://www.toaelectronics.com/products/Amplifiers/power-amplifier/da-series-multi-channel-digital-amplifiers/da-250dhhttp://www.toaelectronics.com/products/Amplifiers/power-amplifier/da-series-multi-channel-digital-amplifiers/da-250f
http://www.toaelectronics.com/products/Amplifiers/power-amplifier/da-series-multi-channel-digital-amplifiers/da-250fh
http://www.toaelectronics.com/products/Amplifiers/power-amplifier/da-series-multi-channel-digital-amplifiers/da-500f-hl
http://www.toaelectronics.com/products/Amplifiers/power-amplifier/da-series-multi-channel-digital-amplifiers/da-550f

**Comment by TOABridget** [comment]
Lower left? There might only be 1 image for that product and if that's the case, only 1 will show and there will be nothing to scroll because there is only 1 image.

**Comment by rescobar2** [comment]
Lower image missing for all URLS
<img src="../media/da-rack.jpg" alt="" width="200" height="274">

**Comment by TOABridget** [comment]
What image??

**Comment by rescobar2** [comment]
Erin can you please work with Bridget. File appears missing in IE and Chrome, Firefox hides the issue.
Bridget says file is in CMS on the product page.

**Comment by ecommarato** [comment]
Found the problem - it was a broken link issue.  The image now appears in all browsers.

**Comment by rescobar2** [comment]
Verified as fixed, closed
